### ISSUE TITLE
The requirements.txt is wrong.

### ISSUE THREAD

**Issue by abhhba999** [idrblab/rnaincoder#4]
Wrong paths were provided. I can't setup by this txt file.

**Comment by rhondene** [comment]
same; unable to install from requirements.txt
```
(rnaincoder) sh-4.2$ pip install -r requirements.txt 
Processing /home/builder/ktietz/aggregate/tensorflow_recipes/ci_cpu/tensorflow-base_1614354478017/work/tensorflow_pkg/tensorflow-2.4.1-cp38-cp38-linux_x86_64.whl (from -r requirements.txt (line 1))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/builder/ktietz/aggregate/tensorflow_recipes/ci_cpu/tensorflow-base_1614354478017/work/tensorflow_pkg/tensorflow-2.4.1-cp38-cp38-linux_x86_64.whl'
```

**Comment by Yunxia-wang** [comment]
As for this question, I think it would be better to install the package one by one.

**Comment by rhondene** [comment]
dependency conflicts 
<img width="1165" alt="Image" src="https://github.com/user-attachments/assets/a114865a-216b-4a17-8021-26fe950cf57c" />

**Comment by rhondene** [comment]
@Yunxia-wang @abhhba999  I edited the requirements.txt and this worked for me without error

[fixed_requirements.txt](https://github.com/user-attachments/files/19817002/fixed_requirements.txt)

:

**Comment by rhondene** [comment]
**ModuleNotFoundError: No module named 'methods.Methods_all_16_methods'**

```
(rnaincoder) sh-4.2$ python rnaincoder.py --help

Traceback (most recent call last):
  File "rnaincoder.py", line 3, in <module>
    from utility import RNAcoding_01,model
  File "......../RNAcoding_01.py", line 14, in <module>
    import methods.Methods_all_16_methods as Methods_all
(rnaincoder) sh-4.2$ 
```
